### ISSUE TITLE
MSFT support on this

### ISSUE THREAD

**Issue by jakubsuchybio** [2mas/SelectNextOccurrence#10]
Hi,
I just commented on exactly this extension here:
https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/4408859-native-multi-editing-multiple-cursors-and-selecti
At that time I wasn't avare of this extension sorry :(

I somehow got into contact with some Visual Studio Program Manager from MSFT and got 2 hour call with him about all features that this extension provides.
I am not quite sure how you do the multi-caret, I will have to analyze your source tommorow, however I was told, that there should be some proper multi-caret support in VS editor for handling multiple carets. So in the near future this extension could get a proper API support with some really fast editing.

Looking forward to it and if you could contact me on biosek@pm.me I am sure that VS PM from MSFT would totally liked to talk to you @2mas 
Thanks!
P.S.: Also I will be definitely contributing to this extension

**Comment by 2mas** [comment]
Hi! I just replied to your email. I’d be happy to help if someone needs it. 

You are welcome to contribute, there are a couple issues that I havent had alot of time to work on that would make the extension better
