### ISSUE TITLE
Using arrow keys when using multiple cursors

### ISSUE THREAD

**Issue by Chewieez** [2mas/SelectNextOccurrence#11]
### Installed product versions
- Visual Studio:2017 Enterprise 15.8.0 Preview 3.0
- This extension: 1.3.31

### Description
If you use Alt-Click to add multiple cursors, and then use the arrow keys, all the cursors do not move as one on the initial arrow key press

### Steps to recreate
1. Alt+Click to select multiple cursors directly underneath the first cursor.
2. Carefully watch the cursors and press the left arrow key

 ### Example GIF of the behavior I see
link: [https://www.dropbox.com/s/9vz2dd060at6lml/multipleCursorIssue.gif?dl=0](https://www.dropbox.com/s/9vz2dd060at6lml/multipleCursorIssue.gif?dl=0)

### Current behavior
The original cursor location does not move the first time you press the arrow key, yet the extra cursors do move on that first arrow key press. All the cursors move in tandem on and after the 2nd arrow key press.

### Expected behavior
All cursors should move in tandem starting with the first arrow key press.

**Comment by 2mas** [comment]
Thanks for taking time to report! I’ll investigate

**Comment by Chewieez** [comment]
Ahh, thanks for looking into it!! I ended up reverting back to using Visual Studio 15.17 and have been using the your extension without any issues for a few days. Thanks for all your hard work! I grew used to those shortcuts in Visual Studio Code, and it's great to have them again in Visual Studio.

**Comment by 2mas** [comment]
Sounds great, nice to hear that :) 
I'll keep this issue open until they release the new version and all works as expected

**Comment by 2mas** [comment]
This has finally been resolved in VS 2022, no action needed from our code since this seem to have originated from somewhere in VS internal code. Thanks for reporting! :)
