### ISSUE TITLE
Feature request: Command to insert a generated sequence of values across carets

### ISSUE THREAD

**Issue by drewnoakes** [2mas/SelectNextOccurrence#14]
### Summary

Add command that generates sequences of values to insert across carets.

### Description

Quite a few times I've needed to insert 1, 2, 3, ... across lines or statements. It'd be handy to be able to generate values to insert at each caret.

In it's simplest form, a sequence of increasing integers starting at 0 or 1 would be useful. More exotic sequences with different step sizes, alphabetic members, decimal/octal/hex rendering and so forth. I don't know how this would be feasible without some kind of UI.

**Comment by 2mas** [comment]
Yea I think a ui/dialog would be needed with perhaps some pre-defined possibilities. I’m currently away on vacation, if you want to give it a shot in the meanwhile you’re welcome to. I think it could be a nice feature to add

**Comment by drewnoakes** [comment]
No problem. When I next need this I'll have a think about how it might work. Designing the feature is as important as the implementation.

Enjoy your holidays :)

**Comment by 2mas** [comment]
I'm closing this, I dont think this will get implemented as it takes quite a bit of time to come up with a good UI for this
