### ISSUE TITLE
Copy-paste multiple selections between files

### ISSUE THREAD

**Issue by vii1** [2mas/SelectNextOccurrence#18]
### Installed product versions
- Visual Studio: 2017 community 15.8.1
- This extension: 1.3.43

### Description
Copying multiple selections from a file and pasting in another (or even the same file in a different tab) just pastes the last selection. Maybe a conflict with the new multi-caret support introduced in VS 15.8?

### Steps to recreate
1. Open two files in different tabs, OR open one file and use ``Window -> New Window`` to open a new view in a different tab.
2. Multi-select anything and hit CTRL+C
3. Go to other tab and hit CTRL+V

### Current behavior
Only the contents of the last selection is inserted.

### Expected behavior
The contents of every selection should be inserted, each one in a line.

**Comment by 2mas** [comment]
Hi! Thanks for reporting this, you are absoluteley right about that. 
I have made a fix available in the this build: [1.3.44](http://vsixgallery.com/extensions/NextOccurrence.b213c4e9-b96f-4f9d-b1d6-fa8bc7e9da21/Select%20Next%20Occurrence%20v1.3.44.vsix)

Check it out and see if it works as expected

**Comment by vii1** [comment]
Hi! Sorry for the delay, I was on vacation :)
It works! Thank you!
