### ISSUE TITLE
Undo and skip are not functional

### ISSUE THREAD

**Issue by jaybo** [2mas/SelectNextOccurrence#2]
### Installed product versions
- Visual Studio 2017.5.3 and 2017.5.4
- This extension: 1.1.1.1

### Description
Undo and skip are not functional

### Steps to recreate
1. Multiselect with Ctrl+D works fine. Yippee!
2. Assign Skip (Ctrl+K, Ctrl+D) and Undo (Ctrl+U)  as suggested.
2. Skip (Ctrl+K, Ctrl+D) does nothing.
3. Undo (Ctrl+U) undoes ALL multiselect, and not just the last one as expected.
4. There is a ghostly glowing to the selected text as if it is constantly being redrawn which seem worrisome.

**Comment by 2mas** [comment]
Thanks for your report! Just a quick question about the keybindings; what does it say in the box "Use new shortcut in"? This must be set to Text editor (wich i should put in the instructions)

**Comment by jaybo** [comment]
Ah, that fixed it!  Thanks!  This bug can be closed.

**Comment by 2mas** [comment]
Perfect, Readme is also updated with better instructions. I'll keep that glowing in mind too, and see if i can make it show somehow for me
