### ISSUE TITLE
The "Use multiple carets to edit" is buggy

### ISSUE THREAD

**Issue by doggy8088** [2mas/SelectNextOccurrence#3]
### Installed product versions
- Visual Studio: `2017 Community`
- This extension: `1.1.1.1`

### Description

When I Alt+Click to setup multiple carets to edit, then it will become no response, no input, nothing happen when I typing until I hit Escape key will release this situation.

### Steps to recreate
1. Alt+Click multiple place inside a HTML/Razor page.
2. type anyting
3. no effect.

### Current behavior

When I Alt+Click to setup multiple carets to edit, then it will become no response, no input, nothing happen when I typing until I hit Escape key will release this situation.

### Expected behavior

I expected to edit in multiple place concurrently.

**Comment by doggy8088** [comment]
I finally realized that I also installed [Multi Edit Mode](https://github.com/madskristensen/MultiEdit) extension and this conflict with your [Select Next Occurrence](https://marketplace.visualstudio.com/items?itemName=thomaswelen.SelectNextOccurrence) extension.

I think you may mention your user about this situation.  

Thanks!

**Comment by 2mas** [comment]
Thanks for your report @doggy8088!
I have updated the documentation with a Troubleshooting section, I hope this will do. My intentions was not however for users to have to deactivate any other extensions, so I'll keep this in mind and see if i can solve this in some other non-conflicting way.
