### ISSUE TITLE
Sugerencia combinaciones de tecla `para "SelectNextOccurrence"

### ISSUE THREAD

**Issue by SrDobrais** [2mas/SelectNextOccurrence#33]
### Installed product versions
- Visual Studio: [ 2017 Community 15.9.7 ]
- This : [1.3.69]

### Description
Se sugiere utilizar **[Ctrl + Alt + <]** como comando de SelectNextOccurrence. 
Dado que dicha combinación no existe en Visual Studio 2017 Community.
Por lo que dicha combinación no entrará en conflicto con otras asignaciones.
Así mismo, dicha combinación es fácil de usar con la mano izquierda.

SelectNextOccurrence. ……………………………………………….……........ **[Ctrl + Alt + <]**
SelectNextOccurrence. (InsertNewSelecction w/mouse) ......….. **[Ctrl + Alt + <]** + **[Click Izq.]**
SelectNextOccurrence.SelectAllOcurrences. ………….….….....…….. **[Ctrl + Alt + <]** + **[Ctrl + Alt + Inicio]**
SelectNextOccurrence.ConvertSelectionToMultipleCursors  …... **[Ctrl + Alt + <]** + **[Ctrl + Alt + Insert]**
SelectNextOccurrence.AddCaretAbobe …………...……......….………. **[Ctrl + Alt + <]** + **[Ctrl + Alt + Re Pag]**
SelectNextOccurrence.AddCaretBelow ……………….….….........……. **[Ctrl + Alt + <]** + **[Ctrl + Alt + Av Pag]**
SelectNextOccurrence.SelectNextOccurrence ……….….......….…... **[Ctrl + Alt + <]** + **[Ctrl + Alt + Flecha Der]**
SelectNextOccurrence.SelectPreviousOccurrence ……........……... **[Ctrl + Alt + <]** + **[Ctrl + Alt + Flecha Izq]**
SelectNextOccurrence.SelectNextExactOccurrence ……........…….**[Ctrl + Alt + <]** + **[Ctrl + Alt + Flecha Arr]**
SelectNextOccurrence.SelectPrerviousExactOccurrence …......... **[Ctrl + Alt + <]** +**[Ctrl + Alt + Flecha Abj]**
SelectNextOccurrence.SkipOcurrence …………………………......……. **[Ctrl + Alt + <]** + **[Ctrl + Alt + Fin]**
SelectNextOccurrence.UndolOcurrence …………………………......…. **[Ctrl + Alt + <]** + **[Ctrl + Alt + Retoceso]**

Gracias por tan útil aplicación.
N.B. Siento hacerlo en español, mi inglés es muy malo.

**Comment by 2mas** [comment]
Hola! No hablo bueno español... pero, gracias por la report!

En inglés: Do i get it correct if you mean to provide new suggestions to keybindings of the commands? The provided suggestions of shortcuts are meant to closely mirror sublime text/vs-code to make it easy to switch between these editors and VS. But ofcourse they are all free to bind at users choice :)

**Comment by SrDobrais** [comment]
Nice day:
I don't speak good English either. I am sorry!
If it suggested that the basic command to enter the program was that combination, because it is not used by Visual Studio Community, and thus not interfering with others.
The fact of Compatibilidsad with sublime, is important, but it is more not to overwrite other basic commands of VS [Ctrl + d] for example.
Greetings and again thanks for such useful extension!

**Comment by 2mas** [comment]
Sorry I'll be closing this one, since I think the recommended shortcuts are OK, and it's not automatically changing anything leaving the user unaware, the user has to do it manually and will be able to make a choice, thanks for suggestion!
