### ISSUE TITLE
URL broken on marketplace

### ISSUE THREAD

**Issue by James-E-Adams** [2mas/SelectNextOccurrence#34]
Hi there!

It seems like the download URL is broken on the [market place](https://marketplace.visualstudio.com/items?itemName=thomaswelen.SelectNextOccurrence). It goes to:

https://thomaswelen.gallerycdn.vsassets.io/extensions/thomaswelen/selectnextoccurrence/1.3.69/1550589988048/Select_Next_Occurrence_v1.3.52.vsix

It seems changing it to https://thomaswelen.gallerycdn.vsassets.io/extensions/thomaswelen/selectnextoccurrence/1.3.69/1550589988048/Select_Next_Occurrence_v1.3.69.vsix triggers the correct download.

I don't know much about how the VS market place works so not sure if you have control over that URL. 

Cheers,
James

**Comment by 2mas** [comment]
Hi! Thanks for reporting this, I wasn't aware and you're right it's broken. I dont control the URL, it should be automated and something probably went wrong in the last update while uploading the extension. A new release is coming up soon, I'll have an eye on this

**Comment by James-E-Adams** [comment]
Cool - thanks! 🎉

**Comment by 2mas** [comment]
Updated the extension and now the URL seems to be fine again, I omitted the version-number from the .vsix file to hopefully prevent this in the future

**Comment by James-E-Adams** [comment]
Nice work!
