### ISSUE TITLE
Copy and paste not working as I would expect

### ISSUE THREAD

**Issue by busterwood** [2mas/SelectNextOccurrence#4]
### Installed product versions
- Visual Studio: 2017 Professional
- This extension: 1.1.1.1

### Description
Copy and past does not work as I would expect when multiple selections are active.  It appears to paste the last value selected, rather than the value selected for each line.

### Steps to recreate
Given some text:
```
	INSERTED.ID,
        INSERTED.TICKET_ID,
        INSERTED.QUANTITY,
```
1. select the word `INSERTED`
2. press `ctrl-d` twice to select all occurances
3. press `right` twice to more the cursor to the first letter of the next word
4. press `shift-ctrl-right` to select the next words, i.e. `ID` `TICKET_ID` and `QUANTITY` will now be selected
5. press `ctrl-c` to copy to clipboard
6. press `right` twice to move to after the last comma
7. press `ctrl-v` to paste, `QUANTITY` is pasted on every line

### Current behavior
```
	INSERTED.ID, QUANTITY
        INSERTED.TICKET_ID, QUANTITY
	INSERTED.QUANTITY, QUANTITY
```

### Expected behavior
```
	INSERTED.ID, ID
        INSERTED.TICKET_ID, TICKET_ID
	INSERTED.QUANTITY, QUANTITY
```

**Comment by 2mas** [comment]
Thank you for your report @busterwood!
Indeed that feels abit akward, I'm having some updates coming soon so I'll take a look at this too and see if i can get a fix for it

**Comment by 2mas** [comment]
Please try the latest version, I have included a fix for this
