### ISSUE TITLE
SelectNextOccurrence.AddCareBelow and Above don't work correctly when view hold tabs

### ISSUE THREAD

**Issue by dmayola** [2mas/SelectNextOccurrence#51]
### Installed product versions
- Visual Studio: Visual Studio Professional 2019
- This extension: 1.3.132

### Description
SelectNextOccurrence.AddCareBelow and Above don't work correctly when view hold tabs (as tabs).

### Steps to recreate
1. Example text:
				first line starting with tabs
second line that is not using taps AT the beginning
				third line uses tabs at the beginning
2. Set your caret at the second line, for instance, at the word **AT**.
3. AddCaretAbove or Below
4. Notice you didn't get the caret where you would expect

### Current behavior
Caret is not placed in the same column when possible.
It looks like a tab is a count as a single character, instead of 4 (or whatever tab is configured).

### Expected behavior
It should keep the caret at the same column regardless of using tabs or not.

**Comment by Mr-Badger** [comment]
Using tabs instead of spaces is a bit wonky. I'll take a look at it.

**Comment by Mr-Badger** [comment]
Just a minor status update. I've finished fixing most behaviors related to tabs, and a mix between spaces and tabs. Just finishing up few things before creating a PR, so expect it very soon.

**Comment by Mr-Badger** [comment]
PR for this issue is out #53
