### ISSUE TITLE
Feature request: setting for choosing first or last entry on escape key

### ISSUE THREAD

**Issue by Masafi** [2mas/SelectNextOccurrence#52]
### Installed product versions
- Visual Studio: 2017 Professional 15.9.12
- This extension: 1.3.132

### Description
If you select multiple occurrences with "ctrl+d" (SelectNextOccurrence), and then press escape button, all the cursors are deleted except **last**, that becomes your main cursor. But in sublime text 3, same steps leaves you with **first** cursor (the top one), and this is more convenient for me. So I ask you to do a setting, where you can choose which cursor is left, if you press escape button (basically deselect): first or last.

### Steps to recreate
1. Select some word
2. Press Ctrl+D or what key is bound for "SelectNextOccurrence"
3. Deselect by pressing escape button

### Current behavior
The remaining cursor will be the last cursor in the list

### Expected behavior
I'm asking for a setting where the remaining cursor will be the first cursor in the list

**Comment by Mr-Badger** [comment]
This shouldn't be too hard to add, I'll take a look at this.

**Comment by 2mas** [comment]
Great @Mr-Badger, I think too this should not be very problematic, tell me if i can assist
