### ISSUE TITLE
Feature request: Functionality to delete additional cursors with alt+click

### ISSUE THREAD

**Issue by marko1777** [2mas/SelectNextOccurrence#55]
I would like similar functionality as in Vs Code where you can delete you additionally inserted cursors with alt+left click

**Comment by 2mas** [comment]
Thanks for the request, this should not be very hard to implement and it’s a good feature that I wasn’t aware of. I’ll have a look

**Comment by marko1777** [comment]
Awesome, thanks! :)

**Comment by 2mas** [comment]
Implemented a fix for this in https://github.com/2mas/SelectNextOccurrence/tree/improve-alt-click, however there is some weird behaviour going on when de-selecting an entire selection (seems like the cursor-position is not always correct) so sometimes the wrong selection gets de-selected. I need to do some more testing and see if I can find out why before I can release anything, thanks for patience :)

**Comment by 2mas** [comment]
Please test the latest CI-release and see if this is what you're looking for: http://vsixgallery.com/extension/NextOccurrence.b213c4e9-b96f-4f9d-b1d6-fa8bc7e9da21/

**Comment by marko1777** [comment]
Exactly! Thank you very much! :)
