### ISSUE TITLE
Unexpected Add Caret Above Behaviour

### ISSUE THREAD

**Issue by CCattano** [2mas/SelectNextOccurrence#60]
### Installed product versions
- Visual Studio: 2019 Professional v16.4.5
- This extension: v1.3.150

### Description
When adding carets above some lines will have two carets added to a single line, usually separated by a few tabs worth of space.

### Steps to recreate
1. Using key binding Shift + Alt + Up_Arrow add multiple carets above the current

### Current behavior
When adding a caret above a caret is added directly above as expected, but on the same line the new caret was added to a second caret is added a few tabs over. This causes me to add characters to additional places I do not want to add characters.

### Demonstration of behavior
![CaretAboveExample](https://user-images.githubusercontent.com/47487276/81304078-3171bc00-9042-11ea-9b37-910cd828227b.gif)

### Expected behavior
Adding a caret above will add only one caret to the line above not two carets to the line above.

**Comment by Mr-Badger** [comment]
This was fixed in #58 and has been merged to master
