### ISSUE TITLE
Unexpected Add Caret Below Behaviour

### ISSUE THREAD

**Issue by CCattano** [2mas/SelectNextOccurrence#61]
### Installed product versions
- Visual Studio: 2019 Professional v16.4.5
- This extension: v1.3.150

### Description
Making a chain of carets via Add Caret Below places the last caret in the chain at the end of the last line, instead of directly below the penultimate caret in the chain. 

### Steps to recreate
1. Create block of text on multiple lines with the same level of indentation
2. Place cursor at start of the first line
3. Add carets below until you reach the last line
4. Last caret in the chain added to the last line of the text block will be placed at the end of the last line, instead of at the beginning of the last line directly below the penultimate caret that was added in the chain.

### Current behavior
When creating a chain of caret by adding carets below the main caret, when the last line in a block of text is reached, the last caret added below is added to the end of the last line instead of being added directly below the previous caret that was added in the chain.

### Gif of observed behavior
![CaretBelowExample](https://user-images.githubusercontent.com/47487276/81304865-41d66680-9043-11ea-9b55-489e230d1e9c.gif)

### Expected behavior
The last caret added in the chain be directly below the penultimate caret in the chain resulting in a straight line of carets in the chain.

**Comment by 2mas** [comment]
Thanks for excellent descriptions, I'll have a look at this

**Comment by 2mas** [comment]
@CCattano Please try [this](http://vsixgallery.com/extensions/NextOccurrence.b213c4e9-b96f-4f9d-b1d6-fa8bc7e9da21/Select%20Next%20Occurrence%20v1.3.156.vsix) version and see if this works as expected:

**Comment by Mr-Badger** [comment]
This was fixed in #58 and has been merged to master

**Comment by 2mas** [comment]
Correct, closing!
