### ISSUE TITLE
Cursor jumps to bottom of screen when attempting to scroll through intellisense options with arrow keys

### ISSUE THREAD

**Issue by ZachIsAGardner** [2mas/SelectNextOccurrence#66]
### Installed product versions
- Visual Studio: 2019 16.8.3
- This extension: 1.3.172

### Description
Cursor jumps to bottom of screen when attempting to scroll through intellisense options with arrow keys.

### Steps to recreate
1. Highlight variable with CTRL+D
2. Delete variable
3. Type in portion of variable, until intellisense pops up and provides some suggestions
4. Try to scroll through intellisense only to have cursor jump to bottom of file.

(If you press escape after step 2, you won't experience this issue. It is however easy to forget to do this, and having your cursor yank you away from your current work is pretty jarring.)

![select_next_error](https://user-images.githubusercontent.com/30502195/102819863-48330c00-43a2-11eb-90c2-80f3202e442d.gif)

### Current behavior
After highlighting a variable with CTRL+D and deleting it, when I next type in the name of a variable and try to scroll through the intellisense window my cursor jumps to the bottom of the file.

### Expected behavior
Scroll through intellisense without cursor jumping to bottom of file.

**Comment by 2mas** [comment]
Thanks for your report! I could reproduce this and made a quick fix for it, please try the latest update and see if it works as expected for you.

I fixed this from my cellphone so I might have to do some more testing later on

**Comment by 2mas** [comment]
Closing
