### ISSUE TITLE
Update for Visual Studio 2022

### ISSUE THREAD

**Issue by ryanbuening** [2mas/SelectNextOccurrence#67]
Was wondering if there are plans to update this extension for VS 2022? Migration guide can be found here: https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension

**Comment by 2mas** [comment]
I had not thought about it yet, but since you ask I'll do it ofcourse :)

**Comment by ryanbuening** [comment]
Installed it on my end and it's working for me. Thanks!
