### ISSUE TITLE
[FeatureRequest] Supports for Microchip/AVR Studio

### ISSUE THREAD

**Issue by prachtan** [2mas/SelectNextOccurrence#69]
### Installed product versions
- Microchip Studio (former AVR Studio, based on Visual Studio Shell 2015)
- This extension: 1.3.175

### Description
Is there any chance to add a support for Microchip / AVR Studio?
This is my favorite extension for VS, but time to time I have to develop a piece of code for AVR microcontrollers and then I realise how I'm addicted from this extension. Because Microchip/AVR Studio is based on VS2015, maybe it could be doable to supports it?

### Current behavior
Doesn't supports.

**Comment by 2mas** [comment]
Hi! Sorry for late reply.

I have never tried Microchip, but the most recent version of this extension dropped support for VS 2015. So the code before the last PR works for 2015. It’s not something I will continue to support but feel free to test it in Microchip.

I initiated a build with the previous version, it’s available here: https://www.vsixgallery.com/extension/NextOccurrence.b213c4e9-b96f-4f9d-b1d6-fa8bc7e9da21/

**Comment by 2mas** [comment]
Closing this since Microchip seem to be a different product built on an older version of VS
