### ISSUE TITLE
Undo behavior differs with multiple cursors

### ISSUE THREAD

**Issue by mihe** [2mas/SelectNextOccurrence#7]
### Installed product versions
- Visual Studio: 15.6.4
- This extension: 1.2.17

### Description
If you write a word or sentence in VS normally, and press Undo, it deletes that entire word/sentence (not entirely sure what they base the grouping on).

However, if you write the same thing with multiple cursors, and press Undo, you instead only delete the last character you wrote. The difference in behavior here is somewhat jarring.

**Comment by SK83RJOSH** [comment]
I did some initial investigation into this issue, and I believe it'll require using the [`IOleUndoManager`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.ole.interop.ioleundomanager?redirectedfrom=MSDN&view=visualstudiosdk-2017) from within [`CommandTarget::ProcessSelections`](https://github.com/2mas/SelectNextOccurrence/blob/fae38287dbe5c3d572ff97608c57179f2967b929/NextOccurrence/Commands/CommandTarget.cs#L150) for the [relevant commands](https://github.com/2mas/SelectNextOccurrence/blob/fae38287dbe5c3d572ff97608c57179f2967b929/NextOccurrence/Commands/CommandTarget.cs#L82). I'm not sure if there's any utilities to recreate the existing behavior used for text grouping, but I suspect you'll have to recreate it manually.

**Comment by 2mas** [comment]
Ah yes this behaviour differs. There is also a possibility to go Sublime-style here I think, and implement a timer to commit an undo-context combined with regular commit-chars.  I'll see if I can come up with something

**Comment by 2mas** [comment]
Closing this as it's been here for five years and I see no way of fixing it at the moment
