### ISSUE TITLE
ReSharper's CamelHumps select option breaks Multiple carat Shift+Ctrl select for multiple carats

### ISSUE THREAD

**Issue by jaguire** [2mas/SelectNextOccurrence#8]
### Installed product versions
- Visual Studio: 2017 Enterprise
- This extension: 1.2.17

### Description
When ReSharper's CamelHumps option is enabled. After placing multiple carats, Shift+Ctrl+Arrow keys only selects for the last carat and not for the others. --- I know this is dealing with another extension but ReSharper is popular enough that you might want to try making this one play well together. Right now I have to choose between having camel selection or multi selection.

### Expected behavior
All carats should select by word, honoring camel case.

(CamelHumps makes Shift+Ctrl+Arrow respect camel casing when selecting words. Disabling CamelHumps makes the multi selection work as expected with words.)

**Comment by 2mas** [comment]
Thanks for reporting, I'm investigating to see if there is something that can be done about it

**Comment by voltaek** [comment]
The same problem happens with the Sub-word Navigation feature of the VSTricks extension. That feature enables navigation via camelCase, PascalCase, and words_with_underscores, and works through you changing your keybinds to use their new commands for navigating text. Hope that helps.

Ref: [VS Tricks](https://marketplace.visualstudio.com/items?itemName=CodeMuncher1.VSTricks) in the VS Marketplace

**Comment by 2mas** [comment]
After update to support Edit.NextSubwordExtend and Edit.PreviousSubwordExtend this seem to work aswell, please reopen if issues are still present
